server:
  port: 8080

spring:
  application:
    name: customer

  datasource:
    username: mataycode
    password: password
    url: jdbc:postgresql://localhost:5432/customer

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  rabbitmq:
    addresses: localhost:5672
  profiles:
    active: default

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true

management:
  tracing:
    sampling:
      probability: 1

logging:
  pattern:
    correlation: "[${spring.application.name:},%X{traceId:-},%X{spanId:-}] "
  include-application-name: false