server:
  port: 8083

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: customer
            uri: lb://CUSTOMER
            predicates:
              - Path=/api/v1/customers/**

management:
  tracing:
    sampling:
      probability: 1
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans


logging:
  pattern:
    correlation: "[${spring.application.name:},%X{traceId:-},%X{spanId:-}] "
  include-application-name: false

#eureka:
#  client:
#    service-url:
#      default-zone: http://eureka-server:8761

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    fetch-registry: true
    register-with-eureka: true