apiVersion: apps/v1
kind: Deployment
metadata:
  name: fraud
  labels:
    app: fraud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fraud
  template:
    metadata:
      name: fraud
      labels:
        app: fraud
    spec:
      containers:
        - name: fraud
          image: matayyy/fraud:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
              protocol: TCP
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: kube
            - name: SPRING_DATASOURCE_USERNAME
              value: linpostgres
            - name: SPRING_DATASOURCE_PASSWORD
              value: learningpassowrd
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://lin-1234-444-pgsql-primary.servers.linodedb.net:5432/fraud
      restartPolicy: Always
